spring:
  cloud:
    gateway:
      # applied globally to all routes.
      globalFilters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter:
            replenishRate: 10 # Number of requests allowed per second.
            burstCapacity: 20 # Maximum number of requests allowed in a burst.

      routes:
        - id: order-service # Unique id of the route. This must be unique
          uri: http://localhost:8080 # Target microservice URI
          predicates: # condition that you want to check before routing to the given URI.
            - Path=/ignored/orders/** # Path predicate for URI path matching
            - Method=GET
            - RemoteAddr=192.168.1.0/24
          filters:
            - StripPrefix=1 # Remove the first segment of the path
  data:
    mongodb:
      uri: mongodb://root:password@localhost:27017
      database: scg

job:
  autorun:
    enabled: true